---
- name: BIGIP | Testes com m칩dulos do bigip
  hosts: bigip
  gather_facts: true
  connection: local
  collections:
    - f5networks.f5_modules

  vars:
    f5_provider:
      server: "{{ inventory_hostname }}"
      user: "{{ f5_user }}"
      password: "{{ f5_password }}"
      server_port: 443
      transport: "rest"
      validate_certs: false
    servidor_destino_scp: "ubuntusrv1.lab.local"
    diretorio_destino_scp: "/backup/F5-backups/"
    ssh_key_file_location: "/etc/security/f5scpkeytoubuntusrv1.key"

  tasks:
    - name: SET FACTS | Seta facts e vari치veis para uso no playbook
      ansible.builtin.set_fact:
        f5_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        f5_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"

    - name: F5 FACTS | Gather facts com m칩dulo F5
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - devices

        provider: "{{ f5_provider }}"
      delegate_to: localhost

    - name: BACKUP | Gera o arquivo de backup UCS no balanceador
      f5networks.f5_modules.bigip_ucs_fetch:
        async_timeout: 600
        only_create_file: true
        src: "{{ inventory_hostname }}_{{ ansible_date_time.date }}.ucs"

        provider: "{{ f5_provider }}"
      delegate_to: localhost

    - name: SCP | Transfere via SCP o arquivo de backup para a m치quina LI2017
      f5networks.f5_modules.bigip_command:
        commands: 'run /util bash -c "scp -i {{ ssh_key_file_location }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /var/local/ucs/{{ inventory_hostname }}_{{ ansible_date_time.date }}.ucs {{ ansible_user }}@{{ servidor_destino_scp }}:{{ diretorio_destino_scp }}"'

        provider: "{{ f5_provider }}"
      delegate_to: localhost
...