---
- name: BIGIP | Testes com módulos do bigip
  hosts: bigip
  gather_facts: false
  collections:
    - f5networks.f5_modules

  vars:
    f5_provider:
      server: "{{ inventory_hostname }}"
      user: "{{ f5_user }}"
      password: "{{ f5_password }}"
      server_port: 443
      transport: "rest"
      validate_certs: false

  tasks:
    - name: SET FACTS | Seta facts e variáveis para uso no playbook
      ansible.builtin.set_fact:
        f5_user: '{{ lookup("env", "ANSIBLE_NET_USERNAME") }}'
        f5_password: '{{ lookup("env", "ANSIBLE_NET_PASSWORD") }}'

    - name: F5 FACTS | Gather facts com módulo F5
      f5networks.f5_modules.bigip_device_info:
        gather_subset:
          - devices

        provider: "{{ f5_provider }}"
      delegate_to: localhost
...